version: '3.4'

services:
  desafiodev-webapi:
    image: desafiodev-webapi
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - 44353:80
    networks:
      - desafiodev-network
networks:
  desafiodev-network:
    driver: bridge